version: '3.7'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=app
      - POSTGRES_DB=db
    ports:
      - 5432:5432
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
  samples:
    build: samples
    image: tx-samples
    environment:
      - DSN=postgres://app:pass@db:5432/db
    depends_on:
      - db