version: '3.7'
services:
  wordpress:
    image: wordpress
    ports:
      - 9999:80
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=user
      - WORDPRESS_DB_PASSWORD=pass
      - WORDPRESS_DB_NAME=db
  db:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
      - MYSQL_RANDOM_ROOT_PASSWORD=secret
